{
 "title": "Docker Monitoring",
 "tags": [
  "Docker",
  "Glances",
  "1"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Andromeda - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "Circinus - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  { "title": "Dashboard Quick Access", "type": "dashlist", "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 } },
  { "title": "Andromeda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Core",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "column": "cpucore",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpucore\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "Andromeda - Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "eth0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Data Rate" }
   ],
   "targets": [
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used\") FROM \"localhost.memswap\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "swap_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") FROM \"localhost.memswap\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "swap_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"user\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "System",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "IoWait",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"iowait\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"min1\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ],
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "5mins",
     "column": "min5",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"min5\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "15mins",
     "column": "min15",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"min15\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "MEM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used\") FROM \"localhost.mem\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") FROM \"localhost.mem\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "/ used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 19 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"/.percent\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "device", "operator": "=", "value": "sda2" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  { "title": "Circinus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Core(s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "column": "cpucore",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpucore\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "Andromeda - Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "eth0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "Data Rate" }
   ],
   "targets": [
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    },
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used\") FROM \"localhost.memswap\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "swap_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") FROM \"localhost.memswap\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "swap_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"user\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "System",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    },
    {
     "alias": "IoWait",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"iowait\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "host", "operator": "=", "value": "andromeda" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"min1\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ],
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "5mins",
     "column": "min5",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"min5\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    },
    {
     "alias": "15mins",
     "column": "min15",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"min15\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "MEM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used\") FROM \"localhost.mem\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") FROM \"localhost.mem\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  },
  {
   "title": "/ used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 36 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"/.percent\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "device", "operator": "=", "value": "sda2" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "circinus" }
     ]
    }
   ]
  }
 ]
}