{
 "title": "Overview",
 "tags": [ "1" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ourl", "query": "https://URLTOOMBI" },
   { "name": "turl", "query": "http://10.9.9.125:8181" },
   { "name": "surl", "query": "http://10.9.9.125:8989" },
   { "name": "rurl", "query": "http://10.9.9.125:7878" }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "content": "<style type=\"text/css\">\r\np.markdown-html.panel-text-content {\r\noverflow: hidden;\r\n}\r\np.markdown-html.panel-text-content iframe {\r\nheight:230px;\r\n}\r\n</style>\r\n<script type=\"text/javascript\">\r\nvar weatherProperties = 'lat=XX.XXXX&lon=-XX.XXXX&color=#FFFFFF&text-color=#FFFFFF';\r\n\r\n// initial load\r\ndocument.getElementById('embedweather').src = 'https://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties;\r\n\r\n// refresh\r\nvar weatherRefresh = setInterval(function() { document.getElementById('embedweather').src = 'https://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties; }, 1800000);\r\n\r\n</script>\r\n<iframe id=\"embedweather\" height=\"100%\" src=\"#\" style=\"margin: 0; padding: 0; border: none; width:100%; position:relative; top:-50px; overflow:hidden; margin-bottom: -50px;\"></iframe>"
  },
  {
   "title": "Guardian - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "transmission_session_stats_active{type=\"cumulative\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    }
   ]
  },
  {
   "title": "SIRIUS - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "transmission_session_stats_active{type=\"cumulative\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SIRIUS" }
     ]
    }
   ]
  },
  {
   "title": "ALPHACENTAURI - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "transmission_session_stats_active{type=\"cumulative\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" }
     ]
    }
   ]
  },
  {
   "title": "Issues Pending",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "WAN Ping",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Quick Access", "type": "dashlist", "gridPos": { "h": 10, "w": 7, "x": 17, "y": 7 } },
  {
   "title": "Movies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Guardian - CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "SIRIUS - CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SIRIUS" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "ALPHACENTAURI - CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" }
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Download Folder Free Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 13 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_free_space{download_dir=\"/downloads/complete\",incomplete_dir=\"/downloads/incomplete\"}"
    }
   ]
  },
  {
   "title": "Guardian - Available RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    }
   ]
  },
  {
   "title": "SIRIUS - Available RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SIRIUS" }
     ]
    }
   ]
  },
  {
   "title": "ALPHACENTAURI - Available RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" }
     ]
    }
   ]
  },
  {
   "title": "Pending Req.",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Data Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 15 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "comcast_data_usage",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN Speedtest - Last 7 Days",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GUARDIAN - TX",
   "type": "singlestat",
   "description": "Thresholds are 100 mbit,500 mbit,1000 mbit",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    }
   ]
  },
  {
   "title": "SIRIUS - TX",
   "type": "singlestat",
   "description": "Thresholds are 10 mbit,50 mbit,100 mbit",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Packets_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    }
   ]
  },
  {
   "title": "ALPHACENTAURI - Plex Storage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Free_Megabytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "LogicalDisk" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "J:" }
     ]
    }
   ]
  },
  {
   "title": "GUARDIAN - RX",
   "type": "singlestat",
   "description": "Thresholds are 100 mbit,500 mbit,1000 mbit",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SIRIUS" }
     ]
    }
   ]
  },
  {
   "title": "SIRIUS - RX",
   "type": "singlestat",
   "description": "Thresholds are 100 mbit,500 mbit,1000 mbit",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SIRIUS" }
     ]
    }
   ]
  },
  {
   "title": "ALPHACENTAURI - RX/TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Intel[R] I350 Gigabit Network Connection TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] I350 Gigabit Network Connection"
      }
     ]
    },
    {
     "alias": "Intel[R] I350 Gigabit Network Connection RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] I350 Gigabit Network Connection"
      }
     ]
    },
    {
     "alias": "Intel[R] I350 Gigabit Network Connection_2 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] I350 Gigabit Network Connection _2"
      }
     ]
    },
    {
     "alias": "Intel[R] I350 Gigabit Network Connection_2 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] I350 Gigabit Network Connection _2"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _2 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _2"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _2 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _2"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _3 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _3"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _3 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _3"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _4 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _4"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _4 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _4"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _5 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _5"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _5 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _5"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _6 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _6"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _6 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _6"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _7 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _7"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _7 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _7"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _8 TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _8"
      }
     ]
    },
    {
     "alias": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _8 RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ALPHACENTAURI" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 PT Quad Port LP Server Adapter _8"
      }
     ]
    }
   ]
  },
  {
   "title": "Alphacentauri Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1" ], "type": "top" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "10.9.9.42" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "p1_dts_therm_mgn" }
     ]
    },
    {
     "alias": "P2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1" ], "type": "top" },
       { "params": [ " / -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "10.9.9.42" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "p2_dts_therm_mgn" }
     ]
    },
    {
     "alias": "SSB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "10.9.9.42" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "ssb_temp" }
     ]
    },
    {
     "alias": "NIC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "10.9.9.42" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "lan_nic_temp" }
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "10.9.9.42" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "bb_mem_vr_temp" }
     ]
    }
   ]
  },
  {
   "title": "CLOUDFLARE URL - RC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "dimensions": "responseCode", "from": "zone", "metrics": [ "queryCount" ], "tag": "CLOUDFLARE URL" }
   ]
  },
  {
   "title": "CLOUDFLARE URL - QPN",
   "type": "graph",
   "description": "Queries per Name",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "dimensions": "queryName", "from": "zone", "metrics": [ "queryCount" ], "tag": "CLOUDFLARE URL" }
   ]
  },
  {
   "title": "Processor Time - Guardian",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Processor_Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    },
    {
     "alias": "DPC_Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_DPC_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    },
    {
     "alias": "Interrupt_Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    },
    {
     "alias": "Privileged_Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    },
    {
     "alias": "User_Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    },
    {
     "alias": "Idle_Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "GUARDIAN" }
     ]
    }
   ]
  },
  {
   "title": "Ombi Requests Pending",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "requested_date" ], "type": "tag" },
      { "params": [ "requested_user" ], "type": "tag" },
      { "params": [ "request_type" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Requests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "0" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Airing Today - TV",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "downloaded" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Future" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"friendly_name\",  \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"",
     "select": [
      [
       { "params": [ "session_key" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 65 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  }
 ]
}