{
 "title": "Transmission Stats",
 "tags": [
  "Transmission",
  "Home",
  "1"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transmission TX/RX Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbits", "label": "Speed in bps" }
   ],
   "targets": [
    {
     "expr": "transmission_session_stats_upload_speed_bytes{instance=\"172.17.0.9:19091\",job=\"transmission\"}",
     "legendFormat": "TX Speed"
    },
    {
     "expr": "transmission_session_stats_download_speed_bytes{instance=\"172.17.0.9:19091\",job=\"transmission\"}",
     "legendFormat": "RX Speed"
    }
   ]
  },
  { "title": "Dashboard Quick Access", "type": "dashlist", "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Total RX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"cumulative\",instance=\"172.17.0.9:19091\",job=\"transmission\"}"
    }
   ]
  },
  {
   "title": "Total TX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\",instance=\"172.17.0.9:19091\",job=\"transmission\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "transmission_session_stats_torrents_active{instance=\"172.17.0.9:19091\",job=\"transmission\"}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "transmission_session_stats_torrents_paused{instance=\"172.17.0.9:19091\",job=\"transmission\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "transmission_session_stats_torrents_total{instance=\"172.17.0.9:19091\",job=\"transmission\"}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proce",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "container_name",
       "operator": "=",
       "value": "composefiles_transmission-openvpn_1"
      }
     ]
    }
   ]
  },
  {
   "title": "MEM %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "proce",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "container_name",
       "operator": "=",
       "value": "composefiles_transmission-openvpn_1"
      }
     ]
    }
   ]
  }
 ]
}